defaults: &DEFAULTS
  domain: localhost:3000 
  dropbox:
    app_key: app_key
    app_secret: app_secret
    polling_interval: 300
  rackspace:
    username: my_username
    api_key: some_crazy_key
    bucket: assets.truebuy.com 
  aws:
    access_key: AKIAJ4WX6PQISTLVZNEQ
    secret_key: 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   
    bucket: "assets.rightbyme"
  analytics:
    google: google_analytics_id
    mixpanel: mixpanel_id
  sendgrid:
    username: sendgrid_username
    password: sendgrid_password
    domain: sendgrid_domain   
  gmail:
    user_name:
    password:     
  mailjet:
    api_key: 117e0fa84c038646b6fa26e85a766322
    secret_key: 487ea9095fdaeaf77a6429938ef0c1cc
    default_from: chip@truebuy.com
  mandrill:
    username:
    api_key:    
  rackspace:
    username: truebuy
    api_key: ggggg
    bucket: rightbyme-prod                
    
development: &DEVELOPMENT
  <<: *DEFAULTS
  domain: localhost:3000 
  aws:
    access_key: AKIAJA6Y6RTHK3JZM3GQ
    secret_key: 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   
    bucket: "truebuy-dev"

test: &TEST
  <<: *DEVELOPMENT
  aws:
    bucket: "truebuy-dev"    
      
cucumber:
  <<: *TEST

staging: &STAGING
  <<: *DEVELOPMENT
  domain: www.truebuy.com 

production:
  <<: *STAGING
  domain: www.truebuy.com 



