
defaults: &DEFAULTS
  domain: localhost:3000 
  dropbox:
    app_key: app_key
    app_secret: app_secret
    polling_interval: 300
  rackspace:
    username: my_username
    api_key: some_crazy_key
    bucket: assets.groupiter.com 
  aws:
    access_key: AKIAJ4WX6PQISTLVZNEQ
    secret_key: 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   
    bucket: "rightbyme/production"
  blitline:
    app_id: application_id
    secet: secret_value
    public_token: a_token
  analytics:
    google: google_analytics_id
    mixpanel: mixpanel_id
  sendgrid:
    username: sendgrid_username
    password: sendgrid_password
    domain: sendgrid_domain
  rackspace:
    username: rightbyme
    api_key: ggggg
    bucket: assets.dev.rightby.me                
    
development: &DEVELOPMENT
  <<: *DEFAULTS
  domain: localhost:3000 
  aws:
    access_key: AKIAJA6Y6RTHK3JZM3GQ
    secret_key: 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   
    bucket: "rightbyme/dev"
  r

test: &TEST
  <<: *DEVELOPMENT
  aws:
    bucket: "rightbyme/test"    
      
cucumber:
  <<: *TEST

staging: &STAGING
  <<: *DEVELOPMENT
  domain: review.rightby.me 

production:
  <<: *STAGING
  domain: review.rightby.me

beta: &BETA
  <<: *STAGING       
  domain: beta.rightby.me
