defaults: &DEFAULTS
  domain: localhost:3000 
  dropbox:
    app_key: app_key
    app_secret: app_secret
    polling_interval: 300
  analytics:
    google: google_analytics_id
    mixpanel: mixpanel_id
  sendgrid:
    username: sendgrid_username
    password: sendgrid_password
    domain: sendgrid_domain   
  gmail:
    user_name:
    password:     
  mailjet:
    api_key: 117e0fa84c038646b6fa26e85a766322
    secret_key: 487ea9095fdaeaf77a6429938ef0c1cc
    default_from: chip@truebuy.com
    domain: truebuy.com
    smtp_host: in.mailjet.com
  mandrill:
    username: truebuy
    api_key:  tDBRHpJOJC0aSsnSSupuAQ
    domain:  truebuy.com
  mailchimp:
    username: truebuy
    api_key: 6e87a6e9c351726564eb72fc930d660c-us6   
  facebook:
    app_key: 109984119186279
    app_secret: 8a7eb02e1c0908c6988c8c5e48c31c76
    callback: "http://localhost:3000"
  twitter:
    consumer_key: PmGym41STsIW4Gg2G4cHmw
    consumer_secret: OXMlrpN1LqQug1OLkAWn9sFIszYJoyaGr8QRd62qk
  aws:
    # also see 1CTX1AKY0EZHAZKYGG82 in aws chipski@mac.com
    access_key: AKIAICUAICIZ65ID27QA
    secret_key: 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   
    bucket: "truebuy-dev"            
    
development: &DEVELOPMENT
  <<: *DEFAULTS
  domain: localhost:3000 

test: &TEST
  <<: *DEVELOPMENT
cucumber:
  <<: *TEST
staging: &STAGING
  <<: *DEVELOPMENT
  domain: www.truebuy.com 

production:
  <<: *STAGING
  domain: www.truebuy.com 
  aws:
    access_key: AKIAICUAICIZ65ID27QA
    secret_key: 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   
    bucket: "truebuy" 
  facebook:
    app_key: 248229361979945
    app_secret: 83ea6278a5516b04c6a5e50f0c5229bb
    callback: "http://www.truebuy.com"




