defaults: &DEFAULTS
  domain: localhost:3000 
  dropbox:
    app_key: app_key
    app_secret: app_secret
    polling_interval: 300
  analytics:
    google: google_analytics_id
    mixpanel: mixpanel_id
  sendgrid:
    username: sendgrid_username
    password: sendgrid_password
    domain: sendgrid_domain   
  gmail:
    user_name:
    password:     
  mailjet:
    api_key: key
    secret_key: secret
    default_from: you@domain.com
    domain: domain.com
    smtp_host: in.mailjet.com
  mandrill:
    username: name
    api_key:  key
    domain:  domain-name.com
  mailchimp:
    username: truebuy
    api_key:    
  facebook:
    app_key: key
    app_secret: secret
    callback: "http://domain.dev"
  twitter:
    consumer_key: key
    consumer_secret: secret
  aws:
   
    access_key: key
    secret_key: secret   
    bucket: "domain-dev"            
    
development: &DEVELOPMENT
  <<: *DEFAULTS
  domain: localhost:3000 

test: &TEST
  <<: *DEVELOPMENT
cucumber:
  <<: *TEST
staging: &STAGING
  <<: *DEVELOPMENT
  domain: truebuy1.herokuapp.com

production:
  <<: *STAGING
  domain: truebuy1.herokuapp.com
  aws:
    access_key: AKIAICUAICIZ65ID27QA
    secret_key: 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   
    bucket: "truebuy" 
  facebook:
    app_key: 248229361979945
    app_secret: 83ea6278a5516b04c6a5e50f0c5229bb
    callback: "http://truebuy1.herokuapp.com"




