# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: truebuy_development
  host: localhost
  pool: 20
  timeout: 5000
  encoding: utf8
  
test: &test
  adapter: postgresql
  encoding: utf8
  database: truebuy_test
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: truebuy_production
  host: localhost